version: "3.3"
services:
  api:
    build: api/
    ports:
      - "8000:5000"
  postgres:
    image: "postgres:14.2"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  client:
    build: client/
    ports:
      - "3000:8080"
